version: "3.8"
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: mysql:5.7
    env_file: .env
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./backups:/backups
    networks:
      - mysql_net

networks:
  mysql_net:
    name: mysql_net
    driver: bridge
